CREATE DATABASE amazon;
USE amazon;

SELECT * FROM customers;
SELECT * FROM inventory;
SELECT * FROM order_items;
SELECT * FROM orders;
SELECT * FROM payments;
SELECT * FROM products;
SELECT * FROM sellers;
SELECT * FROM shippings;

SELECT 
	DISTINCT payment_status
FROM payments;

SELECT * 
FROM orders
WHERE order_id = 6747;

SELECT * 
FROM payments;

SELECT * 
FROM payments
WHERE order_id = 6747;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

ALTER TABLE order_items
ADD COLUMN total_PRICE FLOAT;


SELECT * FROM order_items;

UPDATE order_items
SET total_price = quantity * price_per_unit;
SELECT * FROM order_items;

SELECT p.product_id, p.product_name, 
sum(oi.total_price) AS Total_Price,
count(o.order_id) AS number_
FROM products p
INNER JOIN order_items oi
ON p.product_id = oi.product_id
INNER JOIN orders o
ON oi.order_id = o.order_id
GROUP BY p.product_id, p.product_name;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

SELECT ca.category_id, ca.category_name, sum(oi.total_price) AS total_price,
sum(oi.total_price)/(SELECT SUM(total_price) FROM order_items)*100 AS Percentage_Contribution
FROM category ca
INNER JOIN products p
ON p.category_id = ca.category_id
INNER JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY ca.category_id, ca.category_name 
Order by sum(oi.total_price) DESC
LIMIT 10;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

SELECT c.customer_id, concat(c.first_name, " ",c.last_name) AS Full_name, sum(oi.total_price) AS Total_price ,count(o.order_id) AS No_of_orders,
sum(oi.total_price)/count(o.order_id) AS AOV
FROM customers c
INNER JOIN orders o 
ON c.customer_id = o.customer_id
INNER JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY c.customer_id, concat(c.first_name, " ",c.last_name)
HAVING count(o.order_id)>5;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/

SELECT year_, month_, total_sale as current_month_sale,
LAG(total_sale, 1) OVER(ORDER BY year_, month_) as last_month_sale
FROM(
SELECT MONTH(o.order_date) AS Month_,YEAR(O.ORDER_DATE) AS Year_, SUM(oi.total_price) AS total_sale
FROM orders o
INNER JOIN order_items as oi
ON o.order_id = oi.order_id 
WHERE o.order_date>= current_date()- interval 1 year
GROUP BY MONTH(o.order_date),YEAR(O.ORDER_DATE)
ORDER BY Year_, Month_
)T;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/

SELECT * FROM customers
WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM orders);

-- OR

SELECT *
FROM customers as c
LEFT JOIN
orders as o
ON o.customer_id = c.customer_id
WHERE o.customer_id IS NULL;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/

WITH State_rankings AS
(
SELECT 
	c.state,
	ca.category_name,
	SUM(oi.total_price) as total_sale,
	RANK() OVER(PARTITION BY c.state ORDER BY SUM(oi.total_price) ASC) as rank_
FROM orders as o
INNER JOIN customers as c
ON o.customer_id = c.customer_id
INNER JOIN order_items as oi
ON o.order_id = oi. order_id
INNER JOIN products as p
ON oi.product_id = p.product_id
INNER JOIN category as ca
ON ca.category_id = p.category_id
GROUP BY c.state, ca.category_name
)
SELECT * FROM State_rankings
WHERE rank_ = 1;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

SELECT 
	c.customer_id,
	CONCAT(c.first_name, ' ',  c.last_name) as full_name,
	SUM(total_price) as CLTV,
	DENSE_RANK() OVER( ORDER BY SUM(total_price) DESC) AS cx_ranking
FROM orders as o
INNER JOIN customers as c
ON c.customer_id = o.customer_id
INNER JOIN order_items as oi
ON oi.order_id = o.order_id
GROUP BY c.customer_id, CONCAT(c.first_name, ' ',  c.last_name);

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

SELECT i.inventory_id, p.product_name,
	i.stock as stock_left,
	i.last_stock_date,
	i.warehouse_id
FROM inventory as i
INNER JOIN products p
ON p.product_id = i.product_id
WHERE stock < 10;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
9.Inventory Restock Optimization
Find products likely to go out of stock soon based on current sales velocity.
Challenge: Include the quantity sold by each product and its stock remaining.
*/

WITH product_sales AS
(
    SELECT
        p.product_id,
        p.product_name,
        SUM(oi.quantity) AS total_quantity_sold
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.product_id, p.product_name
)

SELECT
    p.product_name,
    i.stock,
    ps.total_quantity_sold,
    ROUND(i.stock / ps.total_quantity_sold,2) AS stock_ratio
FROM inventory i
JOIN products p
    ON i.product_id = p.product_id
JOIN product_sales ps
    ON p.product_id = ps.product_id
ORDER BY stock_ratio ASC;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

SELECT p.payment_status,
ROUND(count(*)/(SELECT count(*) FROM payments)*100,2) AS Percentage
FROM payments p
INNER JOIN orders o
ON p.order_id = o.order_id
GROUP BY p.payment_status;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/

WITH top_sellers AS
(
SELECT s.seller_id, s.seller_name,round(sum(oi.total_price),2) AS Revenue
FROM sellers s
INNER JOIN orders o 
ON s.seller_id = o.seller_id
INNER JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY s.seller_id, s.seller_name
ORDER BY sum(oi.total_price) DESC
LIMIT 5
),
sellers_reports AS
(
SELECT ts.seller_id,ts.seller_name, o.order_status, count(o.order_status) AS total_orders FROM orders o
INNER JOIN top_sellers ts
ON o.seller_id = ts.seller_id
WHERE o.order_status NOT IN ('Returned','Inprogress')
GROUP BY ts.seller_id,ts.seller_name, o.order_status
)
SELECT seller_id, seller_name,
SUM(CASE WHEN order_status = "Completed" THEN total_orders ELSE 0 END) AS Completed,
SUM(CASE WHEN order_status = "Cancelled" THEN total_orders ELSE 0 END) AS Cancelled,
sum(total_orders) AS total_orders,
SUM(CASE WHEN order_status = "Completed" THEN total_orders ELSE 0 END)/sum(total_orders)*100 AS Percentage
FROM sellers_reports
GROUP BY seller_id, seller_name;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

SELECT p.product_id,p.product_name, 
(sum(oi.total_price - p.cogs*oi.quantity))/sum(oi.total_price)*100 AS Profit_margin,
dense_rank() OVER(ORDER BY (sum(oi.total_price - p.cogs*oi.quantity))/sum(oi.total_price)*100 DESC) AS Rank_
FROM orders o
INNER JOIN order_items as oi
ON o.order_id = oi.order_id
INNER JOIN products p
ON p.product_id = oi.product_id
GROUP BY p.product_id,p.product_name;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/

SELECT p.product_id, p.product_name, count(o.order_status) AS count_,
SUM(CASE WHEN o.order_status = "Returned" THEN 1 ELSE 0 END) AS Returned,
SUM(CASE WHEN o.order_status = "Returned" THEN 1 ELSE 0 END)/count(o.order_status)*100 AS Percentage
FROM orders o
INNER JOIN order_items as oi
ON o.order_id = oi.order_id
INNER JOIN products p
ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY SUM(CASE WHEN o.order_status = "Returned" THEN 1 ELSE 0 END) DESC
LIMIT 10;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
14.Increasing Purchase Trend 
Identify customers whose order value increased continuously for the last 3 orders.
*/

WITH customer_orders AS
(
SELECT c.customer_id, concat(c.first_name," ",c.last_name) AS Full_name, o.order_date,
ROUND(SUM(oi.total_price),2) AS order_value
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
INNER JOIN order_items as oi
ON o.order_id = oi.order_id
GROUP BY c.customer_id, Full_name, o.order_date 
),
lag_data AS
(
    SELECT *,
           LAG(order_value,1) OVER(PARTITION BY customer_id ORDER BY order_date) AS prev1,
           LAG(order_value,2) OVER(PARTITION BY customer_id ORDER BY order_date) AS prev2
    FROM customer_orders
)

SELECT *
FROM lag_data
WHERE order_value > prev1
AND prev1 > prev2;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/

SELECT s.seller_id, s.seller_name, SUM(oi.total_price) AS Sales,
MAX(o.order_date) as last_sale_date,
MAX(oi.total_price) as last_sale_amount
FROM sellers s
INNER JOIN orders o
ON s.seller_id = o.seller_id
INNER JOIN order_items as oi
ON o.order_id = oi.order_id
WHERE o.order_date <= current_date() - interval 6 month
GROUP BY s.seller_id, s.seller_name;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/
SELECT *,
CASE WHEN Returned>5 THEN "Returning" ELSE "New" END
FROM(
SELECT c.customer_id, concat(c.first_name," ", c.last_name) AS Full_name, count(o.order_ID) AS Orders,
sum(CASE WHEN o.order_status = "Returned" THEN 1 ELSE 0 END) AS Returned
FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
INNER JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY c.customer_id,Full_name)T;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/

WITH top_customers AS
(
SELECT c.customer_id, concat(c.first_name, " ", c.last_name) AS full_name, c.state,SUM(oi.total_price) AS Total_value,count(o.order_id) AS No_of_orders
FROM customers c
INNER JOIN orders o
ON c.customer_id= o.customer_id
INNER JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY c.customer_id, full_name, c.state
)
SELECT *FROM(
SELECT *, 
dense_rank() OVER(PARTITION BY state ORDER BY No_of_orders DESC) AS Rank_
FROM top_customers)T
WHERE Rank_<=5;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
18. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/

SELECT s.shipping_id, SUM(oi.total_price) AS Revenue, count(o.order_id) AS No_of_orders,
AVG(datediff(s.shipping_date,o.order_date)) AS Average_delivery_days
FROM shipping s
INNER JOIN orders o
ON s.order_id = o.order_id
INNER JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY s.shipping_id;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
19. Top 10 product with highest decreasing revenue ratio compare to last year(2022) and current_year(2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result
Note: Decrease ratio = cr-ls/ls* 100 (cs = current_year ls=last_year)
*/

WITH last_year AS
(
SELECT p.product_id, p.product_name, sum(oi.total_price) AS Revenue
FROM orders o
INNER JOIN order_items oi
ON oi.order_id = o.order_id
INNER JOIN products p
ON p.product_id = oi.product_id
WHERE YEAR(o.order_date) = 2022
GROUP BY p.product_id, p.product_name
),

current_year AS
(
SELECT p.product_id, p.product_name, sum(oi.total_price) AS Revenue
FROM orders o
INNER JOIN order_items oi
ON oi.order_id = o.order_id
INNER JOIN products p
ON p.product_id = oi.product_id
WHERE YEAR(o.order_date) = 2023
GROUP BY p.product_id, p.product_name
)

SELECT cs.product_id,
ROUND(ls.revenue,2) AS Last_year_Revenue,
ROUND(cs.revenue,2) AS Current_year_Revenue,
round((cs.revenue-ls.revenue)/ls.revenue*100,2) AS Decreasing_ratio
FROM last_year ls
INNER JOIN current_year cs
ON ls.product_id = cs.product_id
ORDER BY (cs.revenue-ls.revenue)/ls.revenue*100 DESC
LIMIT 10;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
20. Month-over-Month Sales Growth
Calculate monthly revenue growth percentage 
Challenge: Include revenue, previous month sales.
*/

WITH monthly_sales AS
(
    SELECT
        DATE_FORMAT(o.order_date,'%Y-%m') AS month_,
        SUM(oi.total_price) AS revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY month_
)

SELECT
    month_,
    revenue,
    LAG(revenue) OVER(ORDER BY month_) AS previous_month_sales,
    ROUND(
        ((revenue - LAG(revenue) OVER(ORDER BY month_)) /
        LAG(revenue) OVER(ORDER BY month_)) * 100,2
    ) AS growth_percentage
FROM monthly_sales;

